import React from 'react'

export const Data = (props) => {
    const data = [
        {
          key: "1",
          profile: "./naruto.jpg",
          name: "Naruto",
          gender: ["Male"],
          email: "Narutoganteng@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "2",
          profile: "./sakura.jpg",
          name: "Sakura",
          gender: ["female"],
          email: "Sakurah@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "3",
          profile: "./kakashi.jpg",
          name: "Kakashi",
          gender: ["Male"],
          email: "kakashisan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "4",
          name: "Madara",
          profile: "./madara.jpg",
          gender: ["Male"],
          email: "Madara@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "5",
          name: "Itachi",
          profile: "./itachi.jpg",
          gender: ["Male"],
          email: "itachi@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "6",
          name: "Hyugan",
          profile: "./hyugan.jpg",
          gender: ["Male"],
          email: "hyuganojutsu@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "7",
          name: "Boruto",
          profile: "./boruto.jpg",
          gender: ["Male"],
          email: "borutosan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "8",
          name: "Boruto",
          profile: "./boruto.jpg",
          gender: ["Male"],
          email: "borutosan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "9",
          name: "Boruto",
          profile: "./boruto.jpg",
          gender: ["Male"],
          email: "borutosan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "10",
          name: "Boruto",
          profile: "./boruto.jpg",
          gender: ["Male"],
          email: "borutosan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "11",
          name: "Boruto",
          profile: "./boruto.jpg",
          gender: ["Male"],
          email: "borutosan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
        {
          key: "12",
          name: "Boruto",
          profile: "./boruto.jpg",
          gender: ["Male"],
          email: "borutosan@gmail.com",
          address: "New York No. 1 Lake Park",
          tags: ["developer"],
        },
      ];
 
}
